# Generated by Django 6.0.6 on 2026-06-14 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_animal', models.CharField(max_length=50, verbose_name='Tipo Animal')),
                ('estagio_vida', models.CharField(choices=[('filhote', 'Filhote'), ('adulto', 'Adulto')], max_length=20, verbose_name='Estágio de Vida')),
                ('data_resgate', models.DateField(verbose_name='Data Resgate')),
                ('forma_resgate', models.TextField(verbose_name='Forma Resgate')),
                ('situacao_atual', models.CharField(choices=[('a_resgatar', 'A Resgatar'), ('em_tratamento', 'Em Tratamento'), ('pronto_adocao', 'Pronto para Adoção')], max_length=20, verbose_name='Situação Atual')),
                ('anuncio_ativo', models.BooleanField(default=True, verbose_name='Anúncio Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('rua', models.CharField(max_length=150, verbose_name='Rua')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('descricao_perfil', models.TextField(blank=True, null=True, verbose_name='Descrição Perfil')),
                ('formas_contato', models.CharField(max_length=200, verbose_name='Contato')),
                ('tipo_colaborador', models.CharField(choices=[('individual', 'Colaborador Individual'), ('ong', 'ONG')], max_length=20, verbose_name='Tipo Colaborador')),
                ('chave_pix', models.CharField(blank=True, max_length=150, null=True, verbose_name='Pix')),
                ('link_whatsapp', models.URLField(blank=True, max_length=300, null=True, verbose_name='Whatsapp')),
                ('endereco_atuacao', models.TextField(blank=True, null=True, verbose_name='Endereço Atuação')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao_Adocao_Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_visita', models.DateTimeField(verbose_name='Data e Hora Visita')),
                ('quantidade_adotar', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('status_solicitacao', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=20, verbose_name='Status')),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.animal')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Relato_Abandono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao_caso', models.CharField(max_length=100, verbose_name='Situação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('horario_ocorrido', models.DateTimeField(verbose_name='Horário Ocorrido')),
                ('estado_animal', models.CharField(max_length=100, verbose_name='Estado do Animal')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('rua', models.CharField(max_length=150, verbose_name='Rua')),
                ('endereco_complemento', models.TextField(blank=True, null=True, verbose_name='Endereço Complemento')),
                ('e_anonimo', models.BooleanField(default=False, verbose_name='Anônimo')),
                ('id_usuario_relatou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data Envio')),
                ('lida', models.BooleanField(default=False)),
                ('id_relato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.relato_abandono')),
                ('id_ong_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='id_ong_resgatou',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.user'),
        ),
    ]
