# Generated by Django 6.0.6 on 2026-06-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('raca', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('contato', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='animais_adocao/')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100)),
                ('raca', models.CharField(max_length=100)),
                ('descricao_ocorrido', models.TextField()),
                ('chave_pix', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='animais_tratamento/')),
            ],
        ),
    ]
