# Generated by Django 6.0.6 on 2026-06-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_animaladocao_animaltratamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaladocao',
            name='cidade',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animaladocao',
            name='estado',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animaladocao',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
