# Generated by Django 6.0.6 on 2026-06-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_animaladocao_cidade_animaladocao_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaladocao',
            name='especie',
            field=models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('passaro', 'Passaro')], default='gato', max_length=100, verbose_name='Espécie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animaladocao',
            name='estagio',
            field=models.CharField(choices=[('filhote', 'Filhote'), ('adulto', 'Adulto')], default='filhote', max_length=20, verbose_name='Estágio de Vida'),
            preserve_default=False,
        ),
    ]
